services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "cachy"
      DISK_SIZE: "25G"
      RAM_SIZE: "15G"
      CPU_CORE: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
